apiVersion: v1
kind: Pod
metadata:
  name: privileged-test-insec
  namespace: audit-zone
  labels:
    test: audit-security
spec:
  containers:
    - name: test
      image: busybox:latest
      command: ["sleep", "3600"]
      securityContext:
        privileged: true
  restartPolicy: Never
