apiVersion: v1
kind: Pod
metadata:
  name: hostpath-test-insec
  namespace: audit-zone
spec:
  containers:
    - name: test
      image: busybox:latest
      command: ["sleep", "3600"]
      volumeMounts:
        - name: kubernetes-manifests
          mountPath: /manifests
  volumes:
    - name: kubernetes-manifests
      hostPath:
        path: /etc/kubernetes/manifests   # манифесты static-подов
        type: Directory
  restartPolicy: Never
