apiVersion: v1
kind: Pod
metadata:
  name: root-uid-test-insec
  namespace: audit-zone
  labels:
    test: audit-security
spec:
  containers:
    - name: test
      image: busybox:latest
      command: ["sleep", "3600"]
      securityContext:
        runAsUser: 0
        runAsNonRoot: false
  restartPolicy: Never
