apiVersion: v1
kind: Namespace
metadata:
  name: dmz-ingress
  labels:
    domain: dmz-ingress
---
apiVersion: v1
kind: Namespace
metadata:
  name: smarthome
  labels:
    domain: smarthome
---
apiVersion: v1
kind: Namespace
metadata:
  name: tenant-core
  labels:
    domain: tenant-core
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    domain: monitoring
