apiVersion: v1
kind: Pod
metadata:
  name: hostpath-test-sec
  namespace: audit-zone
  labels:
    test: audit-security
spec:
  containers:
    - name: test
      image: busybox:latest
      command: ["sleep", "3600"]
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        seccompProfile:
          type: RuntimeDefault
      volumeMounts:
        - name: safe-volume
          mountPath: /data
  volumes:
    - name: safe-volume
      emptyDir: {}
  restartPolicy: Never
